[workspace]
members = ["projects/*"]
default-members = [
    "projects/lpk-core",
]
exclude = [
    "projects/.DS_Store",
]


[workspace.package]
version = "0.0.0"

[profile.release]
lto = true
panic = "abort"
