name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release LPK unpacker
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
#           - os: ubuntu-latest
#             artifact_name: lpk-unpack
#             asset_name: lpk-unpack-linux-amd64
          - os: windows-latest
            artifact_name: lpk-unpack.exe
            asset_name: lpk-unpack.exe
          - os: macos-latest
            artifact_name: lpk-unpack
            asset_name: lpk-unpack-macos

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Build
        run: cargo build --release

      - name: Rename Binary
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            mv target/release/${{ matrix.artifact_name }} target/release/${{ matrix.asset_name }}
          else
            mv target/release/${{ matrix.artifact_name }} target/release/${{ matrix.asset_name }}
            chmod +x target/release/${{ matrix.asset_name }}
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/${{ matrix.asset_name }}