name: Rust

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
#           - os: ubuntu-latest
#             artifact_name: lpk-unpack
#             asset_name: lpk-unpack-linux-amd64
          - os: windows-latest
          - os: macos-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - name: Rust Nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - name: Build
        run: cargo build --release
      - name: Tests
        run: cargo test --release
